project:
  type: book

book:
  title: "The Algorithm Codex"
  author: "Alejandro Piad-Morffis, Ph.D."
  date: "1/17/2026"
  chapters:
    - index.qmd
    - part: Searching and Sorting
      chapters:
      - 01_search.md
    - part: Trees
    - part: Graphs

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
